# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
  desc "A tool for managing and deduplicating media files."
  homepage "https://github.com/yuriykuntsyak/mmedusa"
  version "0.0.15"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.15/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "08f690ed05c6aa4f1df766b3e7794fbfdcd63e158ca605cd47278dad44ea2c64"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.15/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "46b17c09b4d587b29ec915233675be908f22932e6ade2032de8d54db2b6786a9"

      def install
        bin.install "mmedusa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.15/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d618df3d30bb990bc94835f67dc4c9351c0b50b4abb0a618af8a672c13317b18"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.15/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "eb81acc6510fb66ce88c1b26cae268d724ce5bdf22ca542f1fdfb857620548df"

      def install
        bin.install "mmedusa"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end

  test do
    system "#{bin}/mmedusa --help"
  end
end
