# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
  desc "A tool for managing and deduplicating media files."
  homepage "https://github.com/yuriykuntsyak/mmedusa"
  version "0.0.10"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.10/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "365560c34d16924d94c5478b4b9830babf6b09f1d6861a351cf97342db92be22"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.10/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "51d7267bcc011f6f9514b31f466969c840e7d93f4db3cc0598c0ec31c8078704"

      def install
        bin.install "mmedusa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.10/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6ac615a038893dd582739e1a5dab5bc879d6f986b01e3a721060c1fcfff0aec0"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.10/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0a3ae3272b3675e3e27858653ec660f7a7b7d55bcc5212ecb610067907c8cba5"

      def install
        bin.install "mmedusa"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end

  test do
    system "#{bin}/mmedusa --help"
  end
end
