# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
  desc "A tool for managing and deduplicating media files."
  homepage "https://github.com/yuriykuntsyak/mmedusa"
  version "0.0.12"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.12/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0f9e253cba8f92f11af1804840f3c3aeabf2793131ba158caa72daccd04c30aa"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.12/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b568e08f8514b5bc9d24017d01f1f7ca407700da523b2b90cc4e29d1b9237e71"

      def install
        bin.install "mmedusa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.12/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f80ac7579be5e2b4bdadee90f2402b40637734adb2e691c3996baebc5946f8a0"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.12/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "23194f18fdc977a4e3f2cfa9069efe8404be1cd32f7926af9bc0eb37eb98a7be"

      def install
        bin.install "mmedusa"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end

  test do
    system "#{bin}/mmedusa --help"
  end
end
