# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmedusa < Formula
  desc "A tool for managing and deduplicating media files."
  homepage "https://github.com/yuriykuntsyak/mmedusa"
  version "0.0.9"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.9/mmedusa_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "04896509d4e5c1dc69d85c935a1560cd18cdf1c6e7958375940170ac1cda75ec"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.9/mmedusa_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a5912baa9805cb8237e747e9fa6491ad8686602283709d5248d5a380d2166c4f"

      def install
        bin.install "mmedusa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.9/mmedusa_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c0fd5d3e1ec711577c7153626128bb3f776cd382d4f71225da5a0d30b735677d"

      def install
        bin.install "mmedusa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuriykuntsyak/mmedusa/releases/download/v0.0.9/mmedusa_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "3c21cd4123966cf03ff3921ecf7246d4f4930fe360342772d330fd4509957cf8"

      def install
        bin.install "mmedusa"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary
    EOS
  end

  test do
    system "#{bin}/mmedusa --help"
  end
end
